cursor_shape block
shell_integration no-cursor
background_opacity 0.7

map shift+0x20 send_text all \x1b

# Map copy/paste
map ctrl+shift+c no_op
map ctrl+y copy_to_clipboard
map ctrl+p past_from_clipboard

# Use vim as scrollback pager (launch with ctrl+shift_+h)
scrollback_pager nvim - -c "w! /tmp/kitty_scrollback" -c "term ++curwin cat /tmp/kitty_scrollback"

scrollback_lines 10000

allow_remote_control yes

# User site-specific config.
include site.conf
